### PR TITLE
Change enum field automapping to use enum field detection instead

### PR DESCRIPTION
**Pull request by liach**
Now infers for anonymous enclosed enum subclasses like the one found in Gl State Manager.

With new stitich:
infer subclass

With old stitich:
image

Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by asiekierka** [comment]
You want to check for both name and descriptor with enumFields

**Comment by liach** [comment]
Hmm, why isn't the check for accessor enum flag enough?

**Comment by liach** [comment]
Updated as suggested.

**Comment by liach** [comment]
Eh, you killed my pr again @asiekierka

**Comment by liach** [comment]
@asiekierka Updated for latest stitch and removed a little bit of duplicate old code. Also reformatted some stuff with tabs.

**Pull request merged**
