### PR TITLE
Move all weave stuff to stitch

### LINKED ISSUE #2: Merge weave into enigma
Currently, per my experience working on gradle of yarn, stitch and weave have major overlaps for commands and utilities. Since stitch has a more complete framework, I suggest moving all weave content into stitch and archive weave.

### PR DESCRIPTION
**Pull request by liach**
Closes FabricMC/weave#2

In the future, we just need to update stitch when yarn needs. Weave can die in a fire pretty much.

It appears that weave initially was dedicated to enigma compared to stitch, but since weave has much framework duplicated with stitch and stitch has an enigma plugin, it's worthy to merge these two.

Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by liach** [comment]
@asiekierka Pinging you for a review as even modmuss doesn't have a hand on this.

**Comment by asiekierka** [comment]
No. I explicitly made sure Stitch does not depend on Enigma - barring the optional plugin. That is why it was split off from Weave in the first place - to make the resulting JAR much smaller.

**Comment by liach** [comment]
Can weave be refactored to depend on stitch then? That way, at least it saves a few duplicate commands, etc., and the plugin can be moved to weave as well.

**Comment by asiekierka** [comment]
The plan is for all remaining Weave features to go into Enigma itself.

**Pull request closed without merging**
