### PR TITLE
Check to see if the class is mostly mapped, currently only checks fields.

### PR DESCRIPTION
**Pull request by modmuss50**
Output from 19w12a:

```
Skipping mapping in: cvb.x (15/13)
Skipping mapping in: cvb.y (15/13)
```

### CODE REVIEW

**Comment by asiekierka** [comment]
I, uh, I don't like this approach, sorry. It feels like it *wants* to go awry.

**Comment by modmuss50** [comment]
Yes, its far from optimal, it works in the current versions but can easily break. You may have a better idea.

**Comment by modmuss50** [comment]
This was my other change to give everything names, https://github.com/modmuss50/stitch/commit/c15bedb9ca69c668d67efa2e312a3eece47f96ef

It used this method of detecting the 2 field, moving these names out of intermediary and into the place where the tiny mappings are generated in yarn.

**Comment by asiekierka** [comment]
I actually do. Since we don't actually use Intermediary anywhere but building Yarn, I propose that we enact a rule so that intermediary names get replaced if the official, obfuscated name matches the mapped name (so if we map "x" (field_10398348something) to "x", field_10398348something gets stripped at the Yarn process).

Don't forget to add Mojang's non-remapped names at THAT point in the process, NOT in Intermediary.

**Pull request closed without merging**
